### PR TITLE
Feature/add pipeline in git actions

### PR DESCRIPTION
**Pull request by Moraxan**
Added the build pipeline

### CODE REVIEW

**Comment by baraabd** [comment]
Edit code, I've provided all the code you need to change.

**Comment by baraabd** [comment]
To ensure that every branch have high level of code and avoid bugs forward. 

I think Nibras use java verison 19. so we can use the same verion.

**Comment by baraabd** [comment]
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

Inte punkt . använd  - instead 

som du har skrivit utan dubbelt *

**Comment by baraabd** [comment]
Screenshot 2024-11-14 at 20 57 10

**Comment by Moraxan** [comment]
`on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'`
      
     Är koden nu

**Pull request closed without merging**
